### ISSUE TITLE
Why this project ?

### ISSUE THREAD

**Issue by AmitKumarDas** [StackStorm/st2ci#51]
This may be a dumb question.
I wanted to clarify the purpose (or design) of this library.
Is this library meant for Continuous Integration for st2 by using st2 itself ?
If yes, then which version of st2 is used to build the st2ci ?

**Comment by emedvedev** [comment]
Hi! You're correct: this pack implements our internal CI and all the release machinery of StackStorm. "Continuous Integration for st2 by using st2 itself" is accurate, and IIRC we use the latest available version on the build box.

Most of the workflows here are too specific to be reused somewhere else, but we keep this repo public because some people might be curious to know how we implement all this, and curiosity should be rewarded. ❤️

**Comment by AmitKumarDas** [comment]
Its really good to have this repo public.  It shows the real strength of st2. Pretty solid project that I have seen in recent times.
